name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SGX_MODE: SW
  IAS_MODE: DEV

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: âš™ Install protobuf compiler
        run: |
          sudo apt install -y protobuf-compiler

      - uses: actions/checkout@v3
      - name: âš¡ Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v3

      - uses: actions-rs/cargo@v1
        name: ðŸ”¨ Build
        with:
          command: build
          args: --release
        env:
          RUSTFLAGS: '-Copt-level=3 -Crpath=no -Clto=no'

      - uses: actions-rs/cargo@v1
        name: ðŸ”Ž Run unit tests
        with:
          command: test
          args: --release
